#
# Copyright (C) 2025 The pgagroal community
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this list
# of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice, this
# list of conditions and the following disclaimer in the documentation and/or other
# materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors may
# be used to endorse or promote products derived from this software without specific
# prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
# THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

FROM rockylinux:9

ENV TERM=xterm
ENV PGVERSION=17
ENV PATH="/usr/pgsql-${PGVERSION}/bin:${PATH}"

# Enable EPEL & CRB repositories
RUN dnf -y update && \
    dnf -y install --allowerasing epel-release dnf-plugins-core && \
    dnf config-manager --set-enabled epel crb && \
    dnf clean all

RUN dnf -y update && \
    dnf -y install --allowerasing \
      git gcc clang cmake make \
      libev libev-devel openssl-devel systemd-devel \
      zlib zlib-devel libzstd-devel lz4-devel \
      libssh-devel libcurl-devel libatomic \
      python3-docutils bzip2-devel libarchive-devel \
      net-tools check check-devel graphviz \
      doxygen pandoc texlive texlive-latex \
      python3-pip curl ca-certificates wget \
      libasan libubsan libstdc++-devel libgcc glibc-devel \
      gawk coreutils findutils iproute && \
    dnf clean all

RUN pip3 install --no-cache-dir gcovr

RUN dnf -y install --allowerasing \
        https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf -qy module disable postgresql && \
    dnf -y install --allowerasing \
      postgresql${PGVERSION} \
      postgresql${PGVERSION}-server \
      postgresql${PGVERSION}-contrib && \
    dnf clean all

# Prepare PGDATA
RUN mkdir -p /var/lib/pgsql/data && \
    chown -R postgres:postgres /var/lib/pgsql/data

# Copy source and fix permissions
COPY --chown=postgres:postgres . /pgagroal
USER postgres

# Build directory
RUN rm -rf /pgagroal/build && \
    mkdir -p /pgagroal/build /pgagroal/build/log
WORKDIR /pgagroal/build


RUN cmake \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_C_FLAGS="-fsanitize=address -fsanitize=undefined -ftls-model=initial-exec" \
    -DCMAKE_EXE_LINKER_FLAGS="-lasan -lubsan" \
    .. && \
    make -j$(nproc)


CMD ["/bin/bash"]
