{
 "title": "pgagroal dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipeline mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgagroal_pipeline_mode" }
   ]
  },
  {
   "title": "Active connections",
   "type": "gauge",
   "description": "Active connections",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgagroal_active_connections/pgagroal_max_connections"
    }
   ]
  },
  {
   "title": "Session time",
   "type": "bargauge",
   "description": "Session time",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgagroal_session_time_seconds_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "description": "pgagroal state",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgagroal_state", "legendFormat": "state" }
   ]
  },
  {
   "title": "Failed servers",
   "type": "stat",
   "description": "Failed servers",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pgagroal_failed_servers" }
   ]
  },
  {
   "title": "Connection state",
   "type": "timeseries",
   "description": "Connection state",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pgagroal_active_connections", "legendFormat": "active connections" },
    { "expr": "pgagroal_total_connections", "legendFormat": "total connections" },
    { "expr": "pgagroal_max_connections", "legendFormat": "max connections" }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Authentication",
   "type": "timeseries",
   "description": "Authentication details",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    { "expr": "pgagroal_auth_user_success", "legendFormat": "success" },
    { "expr": "pgagroal_auth_user_error", "legendFormat": "error" },
    {
     "expr": "pgagroal_auth_user_bad_password",
     "legendFormat": "bad password"
    }
   ]
  },
  {
   "title": "Client waiting time",
   "type": "timeseries",
   "description": "The waiting time of clients",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pgagroal_wait_time" }
   ]
  },
  {
   "title": "Query rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pgagroal_query_count - (pgagroal_query_count offset 1s)"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "pgagroal_tx_count - (pgagroal_tx_count offset 1s)"
    }
   ]
  },
  { "title": "Internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Send traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pgagroal_network_sent - (pgagroal_network_sent offset 1s)"
    }
   ]
  },
  {
   "title": "Receive traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pgagroal_network_received - (pgagroal_network_received offset 1s)"
    }
   ]
  },
  {
   "title": "Sockets used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "targets": [
    { "expr": "pgagroal_client_sockets", "legendFormat": "client sockets" },
    { "expr": "pgagroal_total_connections", "legendFormat": "server sockets" },
    { "expr": "pgagroal_self_sockets", "legendFormat": "self sockets" }
   ]
  },
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Connection events",
   "type": "timeseries",
   "description": "Connection events",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 52 },
   "targets": [
    { "expr": "pgagroal_connection_error", "legendFormat": "error" },
    { "expr": "pgagroal_connection_kill", "legendFormat": "kill" },
    { "expr": "pgagroal_connection_remove", "legendFormat": "remove" },
    { "expr": "pgagroal_connection_timeout", "legendFormat": "timeout" },
    { "expr": "pgagroal_connection_return", "legendFormat": "return" },
    { "expr": "pgagroal_connection_invalid", "legendFormat": "invalid" },
    { "expr": "pgagroal_connection_get", "legendFormat": "get" },
    {
     "expr": "pgagroal_connection_idletimeout",
     "legendFormat": "idletimeout"
    },
    { "expr": "pgagroal_connection_flush", "legendFormat": "flush" },
    { "expr": "pgagroal_connection_success", "legendFormat": "success" }
   ]
  },
  {
   "title": "Connections per database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 52 },
   "targets": [
    {
     "expr": "sum(pgagroal_connection) by (database) > 0",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Client state",
   "type": "timeseries",
   "description": "Client state",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 61 },
   "targets": [
    { "expr": "pgagroal_client_active", "legendFormat": "active clients" },
    { "expr": "pgagroal_client_wait", "legendFormat": "waiting clients" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Server connections",
   "type": "timeseries",
   "description": "Server connections",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pgagroal_connection) by (database) > 0",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Server errors",
   "type": "timeseries",
   "description": "Server errors",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 70 },
   "targets": [
    {
     "expr": "sum(pgagroal_server_error) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}